[package]
name = "sudachi-front"
version = "0.1.0"
edition = "2024"

[dependencies]
sudachi = { path = "./sudachi.rs/sudachi" }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[main2]]
name = "main2"
path = "src/test.rs"
